## Default values for Traefik
image: traefik
imageTag: 1.7.10

debug:
  enabled: true

ssl:
  enabled: true
  enforced: true

acme:
  enabled: true
  email: devoxxlab@containo.us
  onHostRule: true
  staging: true
  challengeType: tls-alpn-01

dashboard:
  enabled: true
  ingress:
    annotations:
      kubernetes.io/ingress.class: 'nginx'

rbac:
  enabled: true