version: '3'

services:
  lb:
    image: traefik:2.0.0-alpha4
    command:
      - "--api"
      - "--providers.file.directory=/etc/backend-services/traefik"
      - "--providers.file.watch=true"
      - "--providers.docker=true"
      - "--entrypoints=Name:web Address::80"
      - "--entrypoints=Name:web-secure Address::443"
      - "--acme.email=damien@containo.us"
      - "--acme.storage=/acme/acme.json"
      - "--acme.onHostRule=true"
      - "--acme.tlsChallenge=true"
      - "--acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory"
    labels:
      - traefik.enable=false
    read_only: true
    restart: unless-stopped
    tmpfs:
      - /tmp
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /acme
      - ./backend-services:/etc/backend-services:ro
      - /var/run/docker.sock:/var/run/docker.sock
  jenkins:
    build: ./jenkins/
    restart: unless-stopped
    environment:
      JENKINS_ADMIN_EMAIL: advocacy@containo.us
      JENKINS_URL: https://bg.${EXTERNAL_DOMAIN}
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - ./backend-services:/backend-services:rw
    labels:
      - traefik.http.routers.jenkins.rule=Host(`bg.${EXTERNAL_DOMAIN}`)
      - traefik.http.routers.jenkins.entrypoints=web
      - traefik.http.middlewares.redirectscheme-to-https.redirectscheme.scheme=https
      - traefik.http.routers.jenkins.middlewares=redirectscheme-to-https
      - traefik.http.routers.jenkins-secure.tls=true
      - traefik.http.routers.jenkins-secure.rule=Host(`bg.${EXTERNAL_DOMAIN}`)
      - traefik.http.routers.jenkins-secure.entrypoints=web-secure
