<<<<<<< HEAD
# tag::edge[]
=======
>>>>>>> Init BBL Decathlon
version: '2.4'

services:
  edge:
<<<<<<< HEAD
    image: traefik:1.7.10
    # tag::traefik-ssl[]
    command:
      # tag::traefik-entrypoints-http[]
      - "--entryPoints=Name:http Address::80" # Redirect.EntryPoint:https"
      # end::traefik-entrypoints-http[]
      # tag::traefik-entrypoints-https[]
      - "--entryPoints=Name:https Address::443 TLS"
      - "--defaultEntryPoints=https,http"
      # end::traefik-entrypoints-https[]
      # tag::traefik-entrypoints-acme[]
      - "--acme.entryPoint=https"         # Uses LE certificates on the entrypoint "https" .
      - "--acme.email=damien@containo.us" # Specifies the contact email for the certificates.
      - "--acme.storage=acme.json"        # Stores certificates in the file "acme.storage".
      - "--acme.tlsChallenge=true"        # Uses TLS Challenge.
      - "--acme.onHostRule=true"          # Get cert's domain names from frontend rules.
      # end::traefik-entrypoints-acme[]
      - "--docker.domain=demo.containous.cloud"
    labels:
      - "traefik.enable=false"
    # end::traefik-ssl[]
=======
    image: traefik:2.0.0-alpha1
    command:
      - "--configfile=/traefik.toml"
    labels:
      - "traefik.enable=false"
>>>>>>> Init BBL Decathlon
    ports:
      - "80:80"     # The HTTP port
      - "443:443"   # The HTTPS port
    volumes:
<<<<<<< HEAD
      # To communicate with the Docker Engine
      - /var/run/docker.sock:/var/run/docker.sock
  # end::edge[]
  # tag::web[]
  web:
    image: nmengin/web:devoxx
    labels:
      - "traefik.frontend.rule=Path:/"
  # end::web[]
  # tag::jenkins[]
  jenkins:
    image: jenkins/jenkins:2.150.3-alpine
    expose:
      - 8080
      - 50000
    # tag::jenkins-env-opts[]
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
    # end::jenkins-env-opts[]
    labels:
      # tag::jenkins-labels-port[]
      - "traefik.port=8080"
      # end::jenkins-labels-port[]
      # tag::jenkins-labels-rule[]
      - "traefik.frontend.rule=PathPrefix:/jenkins"
      # end::jenkins-labels-rule[]
  # end::jenkins[]
  # tag::gitserver[]
=======
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
  web:
    build: ./web/
    labels:
      - "traefik.frontend.rule=Host:demo.containous.cloud"
  jenkins:
    image: jenkins/jenkins:2.164.1-alpine
    expose:
      - 8080
      - 50000
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
    labels:
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:demo.containous.cloud;PathPrefix:/jenkins"
>>>>>>> Init BBL Decathlon
  gitserver:
    image: gitea/gitea:latest
    expose:
      - "3000"
      - "22"
    environment:
      - ROOT_URL=/gitserver
    labels:
      - "traefik.port=3000"
<<<<<<< HEAD
      # tag::gitserver-labels-rule[]
      - "traefik.frontend.rule=PathPrefixStrip:/gitserver"
      # end::gitserver-labels-rule[]
  # end::gitserver[]
  # tag::ttyd[]
  ttyd:
    image: tsl0922/ttyd
    labels:
      - "traefik.frontend.rule=PathPrefixStrip:/ttyd"
  # end::ttyd[]
=======
      - "traefik.frontend.rule=Host:demo.containous.cloud;PathPrefixStrip:/gitserver"
  ttyd:
    image: tsl0922/ttyd
    labels:
      - "traefik.frontend.rule=Host:demo.containous.cloud;PathPrefixStrip:/ttyd"
>>>>>>> Init BBL Decathlon
