# tag::toml[]
# tag::entrypoints[]
# tag::entrypoint-tls[]
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
# end::entrypoint-tls[]
  [entryPoints.http]
  address = ":80"
# end::entrypoints[]

# tag::acme[]
[acme]
email = "{acme_email}"
storage = "/acme/acme.json"
entryPoint = "https"
# caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"

[acme.tlsChallenge]

[[acme.domains]]
main = "{lab-domain}"
# end::acme[]

# tag::docker[]
[docker]
domain = "{lab-domain}"
watch = true
# end::docker[]
# end::toml[]
