
---
# Source: traefik/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: traefik
  labels:
    app: traefik
spec:
  type: LoadBalancer
  selector:
    app: traefik
  ports:
  - port: 80
    name: web
    targetPort: web
  - port: 443
    name: websecure
    targetPort: websecure
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: traefik-volumeclaim
  namespace: traefik
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi    
---
# Source: traefik/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
  namespace: traefik
  labels:
    app: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik
      terminationGracePeriodSeconds: 60
      containers:
      - image: traefik:v2.1
        name: traefik
        ports:
        - name: web
          containerPort: 80
          protocol: TCP
        - name: websecure
          containerPort: 443
          protocol: TCP
        - name: traefik
          containerPort: 8000
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/traefik
          name: traefik-data
        args:
          - "--entryPoints.web.address=:80"
          - "--entryPoints.websecure.address=:443"
          - "--entryPoints.traefik.address=:8000"
          - "--api.dashboard=true"
          - "--api.insecure=true"
          - "--providers.kubernetescrd"
          - "--certificatesresolvers.default.acme.tlschallenge=true"
          - "--certificatesresolvers.default.acme.email=manuel@containo.us"
          - "--certificatesresolvers.default.acme.storage=acme.json"
          - "--log.level=DEBUG"
      volumes:
      - name: traefik-data
        persistentVolumeClaim:
          claimName: traefik-volumeclaim
