version: '2.4'

services:
  edge:
    image: traefik:1.7.7
    command: --docker # Tells Traefik to listen to docker
    ports:
      - "80:80"     # The HTTP port
      - "443:443"   # The HTTPS port
    volumes:
      # To communicate with the Docker Engine
      - /var/run/docker.sock:/var/run/docker.sock
  web:
    build: ./web/
    expose:
      - "80"
