version: '3'

services:
  reverse-proxy:
    image: traefik:v2.0.0-rc2-alpine
    command:
      - --providers.file
      - --providers.file.filename=/etc/traefik/dync_conf.toml
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./conf:/etc/traefik/

  service1:
    image: containous/whoami
    restart: always
    ports:
      - "8080:80"
  service2:
    image: nginx
    restart: always
    ports:
      - "8081:80"