# tag::edge[]
version: '2.4'

services:
  edge:
    image: traefik:1.7.10
    command:
      - "--docker" # Tells Traefik to listen to docker
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # To communicate with the Docker Engine
      - /var/run/docker.sock:/var/run/docker.sock
  # end::edge[]
  # tag::web[]
  web:
    build:
      context: ./web/
      dockerfile: Dockerfile-v1
    labels:
      - "traefik.frontend.rule=Host:localhost"
  # end::web[]
  # tag::jenkins[]
  jenkins:
    image: jenkins/jenkins:2.164.2-alpine
    expose:
      - 8080
      - 50000
    # tag::jenkins-env-opts[]
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
    # end::jenkins-env-opts[]
    labels:
      # tag::jenkins-labels-port[]
      - "traefik.port=8080"
      # end::jenkins-labels-port[]
      # tag::jenkins-labels-rule[]
      - "traefik.frontend.rule=PathPrefix:/jenkins"
      # end::jenkins-labels-rule[]
  # end::jenkins[]
  # tag::gitserver[]
  gitserver:
    image: gitea/gitea:latest
    expose:
      - "3000"
      - "22"
    environment:
      - ROOT_URL=/gitserver
    labels:
      - "traefik.port=3000"
      # tag::gitserver-labels-rule[]
      - "traefik.frontend.rule=PathPrefixStrip:/gitserver"
      # end::gitserver-labels-rule[]
  # end::gitserver[]
  # tag::ttyd[]
  ttyd:
    image: tsl0922/ttyd:1.4.2-alpine
    labels:
      - "traefik.frontend.rule=PathPrefixStrip:/ttyd"
  # end::ttyd[]
