version: '2.4'

services:
  edge:
    image: traefik:2.0.0-alpha1
    command:
      - "--configfile=/traefik.toml"
    labels:
      - "traefik.enable=false"
    ports:
      - "80:80"     # The HTTP port
      - "443:443"   # The HTTPS port
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
  web:
    build: ./web/
    labels:
      - "traefik.frontend.rule=Host:demo.containous.cloud"
  jenkins:
    image: jenkins/jenkins:2.164.1-alpine
    expose:
      - 8080
      - 50000
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
    labels:
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:demo.containous.cloud;PathPrefix:/jenkins"
  gitserver:
    image: gitea/gitea:latest
    expose:
      - "3000"
      - "22"
    environment:
      - ROOT_URL=/gitserver
    labels:
      - "traefik.port=3000"
      - "traefik.frontend.rule=Host:demo.containous.cloud;PathPrefixStrip:/gitserver"
  ttyd:
    image: tsl0922/ttyd:1.4.2-alpine
    labels:
      - "traefik.frontend.rule=Host:demo.containous.cloud;PathPrefixStrip:/ttyd"
