[auth]
  default_new_user_role = "restrictedcontrol"
  backend = "managed"
  samlEnabled = false
  samlLoginText = ""
  [auth.sessions]
    lifetime_minutes = 60
    renewal_threshold_minutes = 20
    per_user_limit = 0
  [auth.saml]
    idpMetadataURL = ""
    spHost = ""
    rootCerts = ""
    tlsSkipVerify = false

[scheduling_configuration]
  enable_admin_ucp_scheduling = true
  default_node_orchestrator = "swarm"

[tracking_configuration]
  disable_usageinfo = true
  disable_tracking = true
  anonymize_tracking = true
  cluster_label = ""

[trust_configuration]
  require_content_trust = false

[log_configuration]
  level = "INFO"

[audit_log_configuration]
  level = ""
  support_dump_include_audit_logs = false

[license_configuration]
  auto_refresh = false

[cluster_config]
  controller_port = 8443
  kube_apiserver_port = 6443
  swarm_port = 2376
  swarm_strategy = "spread"
  kv_timeout = 5000
  kv_snapshot_count = 20000
  profiling_enabled = false
  external_service_lb = ""
  metrics_retention_time = "24h"
  metrics_scrape_interval = "1m"
  rethinkdb_cache_size = "auto"
  cloud_provider = ""
  cni_installer_url = ""
  pod_cidr = "192.168.0.0/16"
  calico_mtu = "1480"
  ipip_mtu = "1480"
  unmanaged_cni = false
  nodeport_range = "32768-35535"
  azure_ip_count = ""
  custom_kube_api_server_flags = ["--event-ttl=1h0m0s", "--service-node-port-range=30000-32767"]
  custom_kube_controller_manager_flags = [""]
  custom_kubelet_flags = ["--http-check-frequency=20s", "--cgroups-per-qos=false", "--enforce-node-allocatable="]
  custom_kube_scheduler_flags = ["--algorithm-provider=DefaultProvider"]
  local_volume_collection_mapping = false
  manager_kube_reserved_resources = "cpu=1,memory=2Gi,ephemeral-storage=4Gi"
  worker_kube_reserved_resources = "cpu=100m,memory=300Mi,ephemeral-storage=500Mi"