---
apiVersion: specs.smi-spec.io/v1alpha1
kind: HTTPRouteGroup
metadata:
  name: whoami-routes
  namespace: whoami
matches:
- name: all-get
  pathRegex: "/"
  methods: ["GET"]

---
apiVersion: specs.smi-spec.io/v1alpha1
kind: TCPRoute
metadata:
  name: allow-whoami-client
  namespace: whoami

---
kind: TrafficTarget
apiVersion: access.smi-spec.io/v1alpha1
metadata:
  name: whoami
  namespace: whoami
destination:
  kind: ServiceAccount
  name: whoami-server
  namespace: whoami
specs:
- kind: HTTPRouteGroup
  name: whoami-routes
  matches:
  - all-get
- kind: TCPRoute
  name: allow-whoami-client
sources:
- kind: ServiceAccount
  name: whoami-client
  namespace: whoami


