[http.routers.domain-2]
    entryPoints = ["web"]
    rule = "Host(`domain-2.test.com`)"
    service = "app-2"

[http.services.app-2]
    [[http.services.app-2.weighted.services]]
        name = "app-2v1"
        weight = 3
    [[http.services.app-2.weighted.services]]
        name = "app-2v2"
        weight = 1

  [http.services.app-2v1]
      [http.services.app-2v1.loadBalancer]
          [http.services.app-2v1.loadBalancer.healthCheck]
              path = "/check"
              hostname = "domain-2.test.com"
              interval = "10s"
              timeout = "5s"
          [[http.services.app-2v1.loadBalancer.servers]]
              url = "http://s1.test.com/"

  [http.services.app-2v2]
      [http.services.app-2v2.loadBalancer]
          [http.services.app-2v2.loadBalancer.healthCheck]
              path = "/check"
              hostname = "domain-2.test.com"
              interval = "10s"
              timeout = "5s"
          [[http.services.app-2v2.loadBalancer.servers]]
              url = "http://s2.test.com/"