# tag::deployment[]
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: web-deployment
  namespace: devoxx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        guilde: web
        faction: server
    spec:
      containers:
        - name: web-container
          image: nmengin/web:devoxx
          imagePullPolicy: IfNotPresent
# end::deployment[]

# tag::svc[]
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: devoxx
  labels:
    guilde: web
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: web-http
  selector:
    labels:
      guilde: web
      faction: server
# end::svc[]

# tag::ingress[]
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web-ingress
  namespace: devoxx
  labels:
    guilde: web
  annotations:
    kubernetes.io/ingress.class: 'traefik'
spec:
  rules:
  - host: lab.nicolas.containous.cloud
    http:
      paths:
      - path: /
        backend:
          serviceName: web-service
# end::ingress[]