---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: traefik
data:
  traefik.toml: |
    [Global]
      checkNewVersion = false
      sendAnonymousUsage = false
    [log]
      level = "debug"
    [entryPoints]
      [entryPoints.http]
        address = ":80"
      [entryPoints.https]
        address = ":443"
      [entryPoints.tcp]
        address = ":8081"
    [providers]
      [providers.kubernetesCRD]
    [api]
      dashboard = true
      insecure = true
    [metrics]
      [metrics.prometheus]
    [tracing]
      [tracing.jaeger]
        samplingServerURL = "http://jaeger-agent.jaeger.svc.cluster.local:5778/sampling"
        localAgentHostPort = "jaeger-agent.jaeger.svc.cluster.local:6831"
        traceContextHeaderName = "grpc-trace-bin"
        # [tracing.jaeger.collector]
        #   endpoint = "http:/jaeger-agent.jaeger.svc.cluster.local:14268/api/traces?format=jaeger.thrift"

