[global]
  checkNewVersion = false
  sendAnonymousUsage = false

[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.websecure]
    address = ":443"

[providers.kubernetescrd]

[ping]

[metrics.prometheus]

[tracing.jaeger]
    samplingServerURL = "http://jaeger-agent.jaeger.svc.cluster.local:5778/sampling"
    localAgentHostPort = "jaeger-agent.jaeger.svc.cluster.local:6831"

[log]
  # format = "common"
  level = "DEBUG"

# [accessLog]
  # format = "common"

[api]
  insecure = true
  dashboard = true
  debug = true

#[authSources]
  #[authSources.ldapSource]
    #[authSources.ldapSource.ldap]
      #url = "ldap://ldap.ldap.svc.cluster.local:389"
