---

apiVersion: v1
kind: Service
metadata:
  name: webservice
  namespace: devoxx
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: websp
  selector:
    pod: webPOD

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: webingress
  namespace: devoxx
  annotations:
    kubernetes.io/ingress.class: 'traefik'
spec:
  rules:
  - host: lab.nicolas.containous.cloud
    http:
      paths:
      - path: /
        backend:
          serviceName: webservice
          servicePort: 80