version: '3.7'
networks:
  traefikee_net:
    external: true

services:  
  paris:
    image: containous/whoami
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.frontend.rule=Host:webapp.docker.localhost;PathPrefixStrip:/paris"
        - "traefik.port=80"
        - "traefik.passHostHeader=true"
        - "traefik.frontend.headers.customResponseHeaders=Access-Control-Allow-Origin:*||Access-Control-Allow-Headers:Content-Type||Access-Control-Allow-Methods:GET"
    networks:
      - traefikee_net
