version: '3.7'
networks:
  traefikee_net:
    external: true

services:
  whoami:
    image: containous/webapp:powpow
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.frontend.rule=Host:webapp.docker.localhost"
        - "traefik.port=80"
        - "traefik.passHostHeader=true"
        - "traefik.frontend.entryPoints=http,https"
    networks:
      - traefikee_net
