version: "3.7"

networks:
  traefikee_net:
    external: true

services:
  jaeger:
    image: jaegertracing/all-in-one:1.11
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:jaeger.localhost"
        - "traefik.port=16686"
        - "traefik.backend=jaeger"
        - "traefik.docker.network=traefikee_net"
        - "traefik.passHostHeader=true"
        - "traefik.frontend.entryPoints=http,https"
    networks:
      - traefikee_net
  hotrod:
    image: jaegertracing/example-hotrod:1.11
    command: all
    environment:
      JAEGER_AGENT_HOST: "jaeger"
    deploy:
      mode: replicated
      replicas: 2
      labels:
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:hotrod.localhost"
        - "traefik.port=8080"
        - "traefik.backend=hotrod"
        - "traefik.docker.network=traefikee_net"
        - "traefik.passHostHeader=true"
        - "traefik.frontend.entryPoints=http,https"
    networks:
      - traefikee_net
