version: '3'

networks:
  webshell-bastion-provision_default:
    external: true

services:
  webshell:
    image: webshell
    user: devoxx
    networks:
      - webshell-bastion-provision_default
    read_only: true
    volumes:
      - ${HOME}/.ssh/id_rsa:/home/devoxx/.ssh/id_rsa
    labels:
      - "traefik.frontend.rule=Host:${COMPOSE_PROJECT_NAME}.${EXTERNAL_DOMAIN}"
