# tag::deployment[]
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: gitea-full-deployment
  namespace: devoxx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        guilde: git
        faction: server
    spec:
      containers:
        - name: gitea-full-container
          image: gitea/gitea:latest
          imagePullPolicy: IfNotPresent
          env:
          - name: ROOT_URL
            value: "/gitserver"
# end::deployment[]

# tag::svc[]
---
apiVersion: v1
kind: Service
metadata:
  name: gitea-full-server
  namespace: devoxx
  labels:
    guilde: git
spec:
  type: ClusterIP
  ports:
    - port: 3000
      name: gitea-http
    - port: 22
      name: gitea-ssh
  selector:
    guilde: git
    faction: server
# end::svc[]

# tag::ingress[]
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gitea-full-ingress
  namespace: devoxx
  labels:
    guilde: git
  annotations:
    kubernetes.io/ingress.class: 'traefik'
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: {lab-domain}
    http:
      paths:
      - path: /gitserver
        backend:
          serviceName: gitea-full-server
          servicePort: gitea-http
# end::ingress[]
