---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: webapp
  namespace: front
  labels:
    app: webapp
spec:
  entryPoints:
    - web
    #- websecure
  routes:
  - match: Host(`webapp.docker.localhost`)
    kind: Rule
    services:
    - name: webapp
      port: 80
  #tls:
    #certResolver: myLE
