version: '3.7'

services:
  traefik:
    image: traefik:v2.1
    depends_on:
      - pebble
    environment:
      - LEGO_CA_CERTIFICATES=/ssl/pebble.minica.pem
      - LEGO_CA_SERVER_NAME=pebble
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker
      - --api.insecure
      - --certificatesresolvers.leresolver.acme.caserver=https://pebble:14000/dir
      - --certificatesresolvers.leresolver.acme.email=your@email.com
      - --certificatesresolvers.leresolver.acme.storage=/acme.json
      - --certificatesresolvers.leresolver.acme.tlsChallenge=true
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./ssl/:/ssl"
    networks:
      default:
        aliases:
          - whoami.localhost
          - traefik.localhost
    labels:
      # Dashboard
      traefik.http.routers.traefik.rule: Host(`traefik.localhost`)
      traefik.http.routers.traefik.entrypoints: websecure
      traefik.http.routers.traefik.service: api@internal
      traefik.http.routers.traefik.tls.certresolver: leresolver
      traefik.http.routers.traefik.middlewares: authtraefik

      traefik.http.middlewares.authtraefik.basicauth.users: user:$$apr1$$q8eZFHjF$$Fvmkk//V6Btlaf2i/ju5n/ # user/password

      # global redirect to https
      traefik.http.routers.http-catchall.rule: hostregexp(`{host:.+}`)
      traefik.http.routers.http-catchall.entrypoints: web
      traefik.http.routers.http-catchall.middlewares: redirect-to-https

      # middleware redirect
      traefik.http.middlewares.redirect-to-https.redirectscheme.scheme: https

  app:
    image: containous/whoami:v1.4.0
    depends_on:
      - traefik
    labels:
      traefik.http.routers.app.rule: Host(`whoami.localhost`)
      traefik.http.routers.app.middlewares: auth
      traefik.http.routers.app.entrypoints: websecure
      traefik.http.routers.app.tls.certresolver: leresolver
      
      traefik.http.middlewares.auth.basicauth.users: user:$$apr1$$q8eZFHjF$$Fvmkk//V6Btlaf2i/ju5n/ # user/password

  pebble:
    image: letsencrypt/pebble:v2.3.0
    command: pebble -config /pebble/config.json
    ports:
      - 14000:14000
    environment:
      # https://github.com/letsencrypt/pebble#testing-at-full-speed
      - PEBBLE_VA_NOSLEEP=1
      # https://github.com/letsencrypt/pebble#invalid-anti-replay-nonce-errors
      - PEBBLE_WFE_NONCEREJECT=0
    volumes:
      - "./pebble:/pebble"


# Dashboard (https://localhost:8080)
# Route
# Basic auth (login: user | password: password)
# Let's Encrypt (https://whoami.localhost/)
# Global HTTP to HTTPS redirection (http://whoami.localhost/)
# Dashboard [api@internal] (http://traefik.localhost/)
# Dashboard [api@internal] + Basic auth (login: user | password: password)
