version: '3.7'

services:
  traefik:
    image: traefik:v2.1
    command:
      - --entrypoints.web.address=:80
      - --providers.docker
      - --api.insecure
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  app:
    image: containous/whoami:v1.4.0
    labels:
      traefik.http.routers.app.rule: Host(`whoami.localhost`)
      traefik.http.routers.app.middlewares: auth
      
      traefik.http.middlewares.auth.basicauth.users: user:$$apr1$$q8eZFHjF$$Fvmkk//V6Btlaf2i/ju5n/ # user/password

# Dashboard (http://localhost:8080)
# Route (http://whoami.localhost/)
