---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: devoxx
  labels:
    guilde: ci
spec:
  type: ClusterIP
  ports:
    - port: 8080
      name: jenkins-http
    - port: 50000
      name: jenkins-admin
  selector:
    guilde: ci
    faction: jenkins

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins-ingress
  namespace: devoxx
  labels:
    guilde: ci
  annotations:
    kubernetes.io/ingress.class: 'traefik'
spec:
  rules:
  - host: lab.nicolas.containous.cloud
    http:
      paths:
      - path: /jenkins
        backend:
          serviceName: jenkins-service
          servicePort: 8080