apiVersion: v1
kind: Service
metadata:
  name: {{ template "traefikee.controlNodesServiceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name | quote}}
    chart: {{ include "traefikee.chartLabel" . | quote }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  ports:
    - name: control-node-protocol
      port: {{ .Values.ports.control }}
  selector:
    component: control-nodes
    app: {{ .Release.Name | quote}}
    release: {{ .Release.Name | quote}}
